### ISSUE TITLE
Errors when installing dependencies for go random package

### ISSUE THREAD

**Issue by annumberhocker** [terraform-ibm-modules/terraform-ibm-issue-tracker#6]
Error: 
```
Run go get -u "github.com/gruntwork-io/terratest/modules/random"
# github.com/zclconf/go-cty/cty/set
Error: ../../../go/src/github.com/zclconf/go-cty/cty/set/iterator.go:3:17: syntax error: unexpected any, expecting ]
Error: ../../../go/src/github.com/zclconf/go-cty/cty/set/iterator.go:8:19: syntax error: unexpected [, expecting comma or )
Error: ../../../go/src/github.com/zclconf/go-cty/cty/set/iterator.go:12:19: syntax error: unexpected [, expecting comma or )
Error: Process completed with exit code 2.
```

Git action logs: 
https://github.com/terraform-ibm-modules/terraform-ibm-cloudpak-integration/runs/6961086846?check_suite_focus=true

**Comment by annumberhocker** [comment]
This fixes the problem.  However, this probably needs to be updated at the template level.  Where did https://github.com/terraform-ibm-modules/terraform-ibm-module-template/tree/main/.github/workflows/test.yaml go?  

For reference in the event that the cloudpak_integration module gets blown away, `https://github.com/terraform-ibm-modules/terraform-ibm-cloudpak-integration/blob/main/.github/workflows/test.yml`:
```
name: "test-scheduler"

on:
  workflow_dispatch:


  schedule:
    - cron:  '*/30 5 * * *'    # triggers the workflow every day at 5:30 UTC

# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

jobs:
  continuous-tests:
    name: Run Test cases
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout                      # action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: |
         go get -u "github.com/gruntwork-io/terratest/modules/random"
         go get -u "github.com/gruntwork-io/terratest/modules/terraform"

      -
        name: setup terraform
        uses: hashicorp/setup-terraform@v1  # sets up Terraform CLI in your GitHub Actions workflow
        with:
          terraform_version: 0.13.0

      - name: Run Test
        working-directory: test
        shell: bash
        run: go test -timeout 2h -v ./...
        env:
          IC_API_KEY: ${{ secrets.ACCESS_KEY }}
          CP_ENTITLEMENT: ${{ secrets.CP_ENTITLEMENT }}
          CP_ENTITLEMENT_EMAIL: ${{ secrets.CP_ENTITLEMENT_EMAIL }}
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Integration Test # default: 8398a7@action-slack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
```
